name: cheetah_core
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/cheetah-projects/cheetah-core

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  analyzer: ^7.3.0
  build: ^2.4.2
  build_config: ^1.1.2
  build_runner_core: ^8.0.0
  intl: ^0.20.2
  meta: ^1.16.0
  source_gen: ^2.0.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^5.0.0
  test: ^1.24.0
